name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3

        - name: Use Node.js 20
          uses: actions/setup-node@v3
          with:
            node-version: 20

        - name: Install depencies
          shell: bash
          run: npm install

        - name: Install spin
          uses: engineerd/configurator@v0.0.8
          with:
            name: "spin"
            url: "https://github.com/fermyon/spin/releases/download/v2.5.1/spin-v2.5.1-linux-amd64.tar.gz"
            pathInArchive: "spin"

        - name: Build
          shell: bash
          run: npm run build

        - name: Test
          shell: bash
          run: npm run test
