name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3

        - name: Use Node.js 22
          uses: actions/setup-node@v3
          with:
            node-version: 22

        - name: Install depencies
          shell: bash
          run: npm install

        - name: Setup `spin`
          uses: fermyon/actions/spin/setup@v1

        - name: Build
          shell: bash
          run: npm run build

        - name: Test
          shell: bash
          run: npm run test
